version: '3'
services:
  postgres:
    image: postgres:13.0-alpine
    hostname: postgres
    container_name: pg_demo
    restart: always
    env_file:
      - ./../.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: demo